version: 2
workflows:
  version: 2
  test:
    jobs:
      - py36
      - py37

jobs:
  py36: &test-template
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.7

    steps:
      - checkout

      # - restore_cache:
      # -   key: v1-dependencies-{{ checksum "simple_model/__version__.py" }}

      - run:
          name: Install test dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install poetry codecov flake8
            poetry install

      # - save_cache:
      #     paths:
      #       - ./venv
      #     key: v1-dependencies-{{ checksum "simple_model/__version__.py" }}

      - run:
          name: Linters
          command: |
            . venv/bin/activate
            flake8 simple_model tests --ignore=E501

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest

      - run:
          name: codecov
          command: |
            . venv/bin/activate
            codecov

  py37:
    <<: *test-template
    docker:
      - image: circleci/python:3.7.3
